name: '📌 Auto Tag on Master'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
      - '*.md'
      - '.vscode/**'
jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Get manifest version
        id: manifest_version
        run: |
          version=$(jq -r .version public/base.manifest.json)
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.manifest_version.outputs.version }}
          RELEASE_BRANCHES: ^(master|main)$
          DEFAULT_BUMP: patch

      - name: Update manifest.json
        run: |
          new_version=$(echo "${{ steps.tag_version.outputs.new_tag }}" | sed 's/^v//')
          jq --arg version "$new_version" '.version = $version' public/base.manifest.json > public/base.manifest.json.tmp && mv public/base.manifest.json.tmp public/base.manifest.json
          git config --global user.name 'Hackertab CI bot'
          git config --global user.email '2389584+medyo@users.noreply.github.com'
          git commit -am "Bump manifest version to $new_version" || echo "No changes"
          git push
